name: Update Naukri Profile

on:
  push:
    branches:
      - main  # This will trigger the workflow when code is pushed to the main branch
  schedule:
    - cron: '0 0 * * *'  # This will run the script every day at midnight (UTC)

jobs:
  run_script:
    runs-on: ubuntu-latest  # You can change this to a different environment (e.g., windows-latest)
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can change this to the Python version you use

    - name: Install dependencies
      run: |
        pip install selenium

    - name: Download ChromeDriver
      run: |
        sudo apt-get install -y software-properties-common
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        wget "https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.42/linux64/chromedriver-linux64.zip"
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run the script
      env:
        NAUKRI_USERNAME: ${{ secrets.NAUKRI_EMAIL }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
      run: |
        python update_naukri.py  # Run your Python script
