name: Update Resume on Naukri

on:
  push:
    paths:
      - 'resume.pdf'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium

      - name: Download Chrome and ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver

      - name: Run upload script
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        run: |
          python update_naukri.py
